// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "1 - Semaine 1",
      id: "cours/semaine1", // Doit matcher le nom du document qui est dans docs/01-cours/. Les chiffres au début (ex : 01-) sont ignorés.
      customProps: { // Attention, il faut recompiler à chaque modification dans sidebar.js pour que les modifications s'appliquent.
        calendrier: {
          "Calendrier": [
            {"1010": "2026-01-22"}  // Date du cours pour le groupe 1010 du le Prof 1
          ]
        },
        tooltip: "visible" // Valeurs possibles visible ou cache, valeur par défaut "visible"
      }
    },
    {
      type: "doc",
      label: "2 - Semaine 2",
      id: "cours/semaine2",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-01-29"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "3 - Semaine 3",
      id: "cours/semaine3",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-02-05"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "4 - Semaine 4",
      id: "cours/semaine4",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-02-12"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "5 - Semaine 5",
      id: "cours/semaine5",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-02-19"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "6 - Semaine 6",
      id: "cours/semaine6",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-02-26"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "7 - Semaine 7",
      id: "cours/semaine7",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-03-05"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "8 - Semaine 8",
      id: "cours/semaine8",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-03-12"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "9 - Semaine 9",
      id: "cours/semaine9",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-03-26"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "10 - Semaine 10",
      id: "cours/semaine10",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-04-09"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "11 - Semaine 11",
      id: "cours/semaine11",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-04-16"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "12 - Semaine 12",
      id: "cours/semaine12",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-04-23"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "13 - Semaine 13",
      id: "cours/semaine13",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-04-30"}
          ]
        }
      }
    },
    {
      type: "doc",
      label: "14 - Semaine 14",
      id: "cours/semaine14",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-05-07"}
          ]
        }
      },
      "className": "remise-tp2"
    },
    {
      type: "doc",
      label: "15 - Semaine 15",
      id: "cours/semaine15",
      customProps: {
        calendrier: {
          "Calendrier": [
            {"1010": "2026-05-21"}
          ]
        }
      },
      "className": "examen"
    }
  ],
  "tp": [
    {
      type: "autogenerated",
      "dirName": "02-tp"
    }
  ]
};

module.exports = sidebars;
